### ISSUE TITLE
Class constructor Doc cannot be invoked without 'new'

### ISSUE THREAD

**Issue by CatchLife** [Leecason/element-tiptap#183]
版本："element-tiptap": "^1.26.0",
按照文档的代码直接粘贴的，报错
```
TypeError: Class constructor Doc cannot be invoked without 'new'

TypeError: Class constructor Extension cannot be invoked without 'new'
```
经过修改官方的codesandbox的"element-tiptap": "1.25.3",为"element-tiptap": "1.26.0",一样会报错，并且无法正常显示编辑器，希望作者在发布新版本前测试一下

还有README中的USAGE中的data(){}的语法都不对，你可以直接粘贴到IDE试试，作为用法介绍最好贴一个正确的入门code

**Comment by sheldonbaby** [comment]
我之前也遇到这个问题了，如果你用ts的话，修改一下tsconfig.json，编译到es6就好了

**Comment by pelkinn** [comment]
I have the same problem. I don't use the type script, please fix it

**Comment by bunajianke** [comment]
> 我之前也遇到这个问题了，如果你用ts的话，修改一下tsconfig.json，编译到es6就好了

不用ts的要怎么办才好，哭了

**Comment by Leecason** [comment]
Sorry, I have fixed the README

**Comment by pelkinn** [comment]
> Sorry, I have fixed the README

surprisingly, editing the documentation does not solve the problem -_-

**Comment by 2ming** [comment]
Class constructor Doc cannot be invoked without 'new'
版本："element-tiptap": "^1.26.1",
还是有相应的问题

**Comment by pelkinn** [comment]
@Leecason, the problem still remains

**Comment by Leecason** [comment]
Is there a problem with `v1.25.3`?

**Comment by pelkinn** [comment]
no, 1.26.1. @2ming gave the link above

**Comment by Leecason** [comment]
`v1.25.3` is ok, `v1.26+` is broken?

**Comment by pelkinn** [comment]
yes

**Comment by pelkinn** [comment]
I'm trying to start the editor at least somehow, it doesn't even work in version 1.25.3, it works in the sandbox, I don't have.
All code is identical to your example
Error in data(): "TypeError: Class constructor Doc cannot be invoked without 'new'"

**Comment by CatchLife** [comment]
一个最直接的测试方法你可以修改sandbox中element-tiptap的依赖版本

**Comment by Leecason** [comment]
I have tried the previous versions such as `v1.18.0`, all them will report this error, all you the same with me?
I'm a little confused now😕, have you ever had a situation like this?

**Comment by Leecason** [comment]
fixed in `v1.26.2`.
Sorry for the delay.
